name: rive_gen
description: A code generator that automatically creates type-safe Dart classes for Rive assets, similar to flutter_gen for images.
version: 1.0.0
homepage: https://github.com/Tuanpluss02/rive_gen
repository: https://github.com/Tuanpluss02/rive_gen
issue_tracker: https://github.com/Tuanpluss02/rive_gen/issues
documentation: https://github.com/Tuanpluss02/rive_gen#readme
environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  build: ^2.4.1
  build_config: ^1.1.1
  source_gen: ^1.4.0
  analyzer: ^6.0.0
  path: ^1.8.3
  glob: ^2.1.2
  dart_style: ^2.3.4
  yaml: ^3.1.2
  args: ^2.4.2

dev_dependencies:
  build_runner: ^2.4.7
  build_test: ^2.2.1
  lints: ^5.0.0
  test: ^1.24.0

executables:
  rive_gen:
